### ISSUE TITLE
up.ps1 throws error

### ISSUE THREAD

**Issue by akilaKathirc** [fluxdigital/Mandalorian.Sitecore.NetCore#1]
[
![image](https://user-images.githubusercontent.com/40282006/186673810-35b99641-8fb6-47f7-a4cf-05c9809d6ce2.png)
](url)

**Comment by fluxdigital** [comment]
Have you installed the pre-requisites listed here? https://doc.sitecore.com/xp/en/developers/100/developer-tools/walkthrough--using-the-getting-started-template.html#install-the-prerequisites

It looks like you don't have docker desktop installed.

**Comment by akilaKathirc** [comment]
![image](https://user-images.githubusercontent.com/40282006/187381158-9f75e4cd-4e1f-4692-a450-340d87998f32.png)

**Comment by akilaKathirc** [comment]
It works. Thanks
